export const ADD_CATEGORY = 'ADD_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const EDIT_CATEGORY = 'EDIT_CATEGORY'
export const COMPLETE_CATEGORY = 'COMPLETE_CATEGORY'
export const GET_CATEGORIES = 'GET_CATEGORIES'

export const ADD_RECIPE = 'ADD_RECIPE'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const EDIT_RECIPE = 'EDIT_RECIPE'
export const COMPLETE_RECIPE = 'COMPLETE_RECIPE'
export const GET_RECIPES = 'GET_RECIPES'

export const LOGIN_USER = 'LOGIN_USER'
export const REGISTER_USER = 'REGISTER_USER'

export const PAGINATE = 'PAGINATE'
